### ISSUE TITLE
Add Vehicle component using Vehicle Body block and Tire blocks

### ISSUE THREAD

**Issue by Isaac-Ito-MW** [mathworks/Simscape-Hybrid-Electric-Vehicle-Model#2]
For the Vehicle component, build a new referenced subsystem using the Vehicle Body block and Tire blocks from Simscape Driveline.

**Comment by miyangcao** [comment]
Hi,  I am learning to build project models with powertrain brockset.Can you share some of the process of building a project? For the large number of subsystems and signals in the project, how to build the organizational structure and reference model step by step?

**Comment by Isaac-Ito-MW** [comment]
There are various ways to organize a large project.

Here is my approach, which may or may nor work for your situation: Put related files under a folder. For example, create "Components" folder and then create "Components > Vehicle", "Components > MotorDriveUnit", etc. Then in each component folder, put a subsystem reference file, a harness model, simulation scripts, test files and so on.

Another approach is to collect similar files in a folder. For example, put subsystem reference files in one folder. Put test files in another folder. I avoid this approach if possible because finding related files for a component is hard.

When you reorganize a large project, it is very useful to keep things working. Make sure all models, scripts, and functions run without errors all the time. Using unit test (and potentially using it in CI) is very helpful for that purpose.

**Comment by miyangcao** [comment]
Thank you for your answer, your reply is very helpful.
I am trying to use the powertrain brockset , do you have any books or materials that can help you learn quickly ? What companies or academics can answer my questions?

**Comment by Isaac-Ito-MW** [comment]
You can ask your questions at MATLAB Answers:
https://www.mathworks.com/matlabcentral/answers/index/
